// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listArtifactsByVersion = `-- name: ListArtifactsByVersion :many
SELECT id, version_id, kind, oss_key, mime, bytes, sha256, created_at
FROM artifacts
WHERE version_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListArtifactsByVersion(ctx context.Context, versionID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Kind,
			&i.OssKey,
			&i.Mime,
			&i.Bytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
