// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCostEvent = `-- name: InsertCostEvent :one
INSERT INTO cost_events (
    task_id, version_id, run_id, seq, kind, resource_name,
    input_tokens, output_tokens, cached_tokens, calls, duration_ms,
    amount_usd, pricing_id, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14
)
ON CONFLICT (run_id, kind, seq) DO NOTHING
RETURNING input_tokens, output_tokens, cached_tokens, calls, duration_ms,
          amount_usd, pricing_id
`

type InsertCostEventParams struct {
	TaskID       pgtype.UUID        `json:"task_id"`
	VersionID    pgtype.UUID        `json:"version_id"`
	RunID        pgtype.UUID        `json:"run_id"`
	Seq          int64              `json:"seq"`
	Kind         string             `json:"kind"`
	ResourceName string             `json:"resource_name"`
	InputTokens  *int64             `json:"input_tokens"`
	OutputTokens *int64             `json:"output_tokens"`
	CachedTokens *int64             `json:"cached_tokens"`
	Calls        *int32             `json:"calls"`
	DurationMs   *int64             `json:"duration_ms"`
	AmountUsd    pgtype.Numeric     `json:"amount_usd"`
	PricingID    pgtype.UUID        `json:"pricing_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

type InsertCostEventRow struct {
	InputTokens  *int64         `json:"input_tokens"`
	OutputTokens *int64         `json:"output_tokens"`
	CachedTokens *int64         `json:"cached_tokens"`
	Calls        *int32         `json:"calls"`
	DurationMs   *int64         `json:"duration_ms"`
	AmountUsd    pgtype.Numeric `json:"amount_usd"`
	PricingID    pgtype.UUID    `json:"pricing_id"`
}

// Idempotent insert keyed on (run_id, kind, seq) — the uniqueness boundary
// after migration 0004_cost_events_kind_unique (matches the Worker's
// per-(run_id, kind) seq namespace per worker-messaging §"Cost Event
// Publisher"). Returns the inserted row's quantity / amount fields so the
// caller can drive the task_costs UPSERT in the same transaction. On
// duplicate delivery the RETURNING set is empty (caller treats pgx.ErrNoRows
// as "duplicate, skip aggregate UPSERT").
func (q *Queries) InsertCostEvent(ctx context.Context, arg InsertCostEventParams) (InsertCostEventRow, error) {
	row := q.db.QueryRow(ctx, insertCostEvent,
		arg.TaskID,
		arg.VersionID,
		arg.RunID,
		arg.Seq,
		arg.Kind,
		arg.ResourceName,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.Calls,
		arg.DurationMs,
		arg.AmountUsd,
		arg.PricingID,
		arg.OccurredAt,
	)
	var i InsertCostEventRow
	err := row.Scan(
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.Calls,
		&i.DurationMs,
		&i.AmountUsd,
		&i.PricingID,
	)
	return i, err
}
