// Package sqlc holds code generated by `sqlc generate`. Sources live in
// `api/queries/`; configuration is in `api/sqlc.yaml`.
//
// On a fresh checkout this directory contains only this doc file. Run
// `make sqlc` to regenerate query code; once generated, this file remains
// as a stable doc anchor and `models.go` / `*.sql.go` will join it.
//
// Hand-written `pgx`/`database/sql` calls are NOT permitted outside the
// Outbox Relayer's batched scan loop (see api-persistence spec, Requirement
// "Typed Query Layer via sqlc").
package sqlc
