// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID        pgtype.UUID        `json:"id"`
	VersionID pgtype.UUID        `json:"version_id"`
	Kind      string             `json:"kind"`
	OssKey    string             `json:"oss_key"`
	Mime      *string            `json:"mime"`
	Bytes     *int64             `json:"bytes"`
	Sha256    *string            `json:"sha256"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Path      *string            `json:"path"`
}

type CostEvent struct {
	ID           int64              `json:"id"`
	TaskID       pgtype.UUID        `json:"task_id"`
	VersionID    pgtype.UUID        `json:"version_id"`
	RunID        pgtype.UUID        `json:"run_id"`
	Seq          int64              `json:"seq"`
	Kind         string             `json:"kind"`
	ResourceName string             `json:"resource_name"`
	InputTokens  *int64             `json:"input_tokens"`
	OutputTokens *int64             `json:"output_tokens"`
	CachedTokens *int64             `json:"cached_tokens"`
	Calls        *int32             `json:"calls"`
	DurationMs   *int64             `json:"duration_ms"`
	AmountUsd    pgtype.Numeric     `json:"amount_usd"`
	PricingID    pgtype.UUID        `json:"pricing_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	Aggregate   string             `json:"aggregate"`
	AggregateID pgtype.UUID        `json:"aggregate_id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Exchange    string             `json:"exchange"`
}

type Pricing struct {
	ID           pgtype.UUID        `json:"id"`
	ResourceKind string             `json:"resource_kind"`
	ResourceName string             `json:"resource_name"`
	Unit         string             `json:"unit"`
	UnitPriceUsd pgtype.Numeric     `json:"unit_price_usd"`
	EffectiveAt  pgtype.Timestamptz `json:"effective_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Task struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Title          string             `json:"title"`
	TaskType       string             `json:"task_type"`
	Status         string             `json:"status"`
	CurrentVersion pgtype.UUID        `json:"current_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type TaskCheckpoint struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	StepSeq   int32              `json:"step_seq"`
	StepName  string             `json:"step_name"`
	State     []byte             `json:"state"`
	OssKey    *string            `json:"oss_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TaskCost struct {
	VersionID      pgtype.UUID        `json:"version_id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	InputTokens    int64              `json:"input_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	CachedTokens   int64              `json:"cached_tokens"`
	ToolCalls      int32              `json:"tool_calls"`
	WallTimeMs     int64              `json:"wall_time_ms"`
	ComputeSeconds int64              `json:"compute_seconds"`
	AmountUsd      pgtype.Numeric     `json:"amount_usd"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TaskEvent struct {
	ID        int64              `json:"id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	VersionID pgtype.UUID        `json:"version_id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Seq       int64              `json:"seq"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TaskRun struct {
	ID             pgtype.UUID        `json:"id"`
	VersionID      pgtype.UUID        `json:"version_id"`
	AttemptNo      int32              `json:"attempt_no"`
	WorkerRunID    pgtype.UUID        `json:"worker_run_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	LastHeartbeat  pgtype.Timestamptz `json:"last_heartbeat"`
	Error          []byte             `json:"error"`
	IdempotencyKey string             `json:"idempotency_key"`
}

type TaskVersion struct {
	ID           pgtype.UUID        `json:"id"`
	TaskID       pgtype.UUID        `json:"task_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	VersionNo    int32              `json:"version_no"`
	Prompt       string             `json:"prompt"`
	Params       []byte             `json:"params"`
	Status       string             `json:"status"`
	IsActive     *bool              `json:"is_active"`
	ArtifactRoot *string            `json:"artifact_root"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Summary      *string            `json:"summary"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
