// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOutboxPending = `-- name: CountOutboxPending :one
SELECT count(*) FROM outbox WHERE status = 'pending'
`

// Used by the outbox_pending gauge.
func (q *Queries) CountOutboxPending(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOutboxPending)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementOutboxAttempt = `-- name: IncrementOutboxAttempt :exec
UPDATE outbox
SET attempts = attempts + 1,
    next_retry_at = $2
WHERE id = $1
`

type IncrementOutboxAttemptParams struct {
	ID          int64              `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

// Records a publish failure: bumps attempts and schedules a retry at next_retry_at.
func (q *Queries) IncrementOutboxAttempt(ctx context.Context, arg IncrementOutboxAttemptParams) error {
	_, err := q.db.Exec(ctx, incrementOutboxAttempt, arg.ID, arg.NextRetryAt)
	return err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (
    aggregate, aggregate_id, topic, payload, exchange
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, status, created_at
`

type InsertOutboxParams struct {
	Aggregate   string      `json:"aggregate"`
	AggregateID pgtype.UUID `json:"aggregate_id"`
	Topic       string      `json:"topic"`
	Payload     []byte      `json:"payload"`
	Exchange    string      `json:"exchange"`
}

type InsertOutboxRow struct {
	ID        int64              `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Append a new outbox row inside the same transaction as the business write
// it triggers. Returns id/status/created_at so the caller can correlate with
// the publisher's metric output.
//
// `exchange` was added by `add-task-control-api` so each row carries its
// own destination exchange (the Relayer no longer keeps a constant).
// Existing callers (createActiveVersion in domain/task/service.go) pass
// `'task.exchange'` explicitly; control writers pass `'task.control'`.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (InsertOutboxRow, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.Aggregate,
		arg.AggregateID,
		arg.Topic,
		arg.Payload,
		arg.Exchange,
	)
	var i InsertOutboxRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET status = 'failed',
    attempts = attempts + 1
WHERE id = $1
`

// Moves an outbox row to terminal failed state after exhausting retries.
func (q *Queries) MarkOutboxFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, id)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox
SET status = 'sent',
    attempts = attempts + 1
WHERE id = $1
`

// Marks an outbox row as successfully published.
func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}

const scanPendingOutbox = `-- name: ScanPendingOutbox :many
SELECT id, aggregate, aggregate_id, topic, payload, status, attempts, next_retry_at, created_at, exchange
FROM outbox
WHERE status = 'pending'
  AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY id
LIMIT $1
`

// Returns up to $1 pending rows whose next_retry_at has elapsed (or is unset),
// ordered by id for stable replay. Used by the Outbox Relayer scan step.
func (q *Queries) ScanPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, scanPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Aggregate,
			&i.AggregateID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.Exchange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
