// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEffectivePricing = `-- name: GetEffectivePricing :one
SELECT id, resource_kind, resource_name, unit, unit_price_usd, effective_at, expires_at
FROM pricing
WHERE resource_kind = $1
  AND resource_name = $2
  AND unit          = $3
  AND effective_at <= $4
  AND (expires_at IS NULL OR expires_at > $4)
ORDER BY effective_at DESC
LIMIT 1
`

type GetEffectivePricingParams struct {
	ResourceKind string             `json:"resource_kind"`
	ResourceName string             `json:"resource_name"`
	Unit         string             `json:"unit"`
	EffectiveAt  pgtype.Timestamptz `json:"effective_at"`
}

// Returns the pricing row in force at $4 for (resource_kind, resource_name,
// unit), or no rows if none. Used by the Cost Service when scoring a
// cost_event at write time.
func (q *Queries) GetEffectivePricing(ctx context.Context, arg GetEffectivePricingParams) (Pricing, error) {
	row := q.db.QueryRow(ctx, getEffectivePricing,
		arg.ResourceKind,
		arg.ResourceName,
		arg.Unit,
		arg.EffectiveAt,
	)
	var i Pricing
	err := row.Scan(
		&i.ID,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Unit,
		&i.UnitPriceUsd,
		&i.EffectiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listCurrentPricing = `-- name: ListCurrentPricing :many
SELECT id, resource_kind, resource_name, unit, unit_price_usd, effective_at, expires_at
FROM pricing
WHERE effective_at <= now()
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY resource_kind, resource_name, unit
`

// All pricing rows in force at now() — the source for GET /api/v1/pricing.
// Owner-agnostic; every authenticated caller receives the same body.
// Ordering is stable so JSON byte-identity across callers holds (S15 test).
func (q *Queries) ListCurrentPricing(ctx context.Context) ([]Pricing, error) {
	rows, err := q.db.Query(ctx, listCurrentPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pricing
	for rows.Next() {
		var i Pricing
		if err := rows.Scan(
			&i.ID,
			&i.ResourceKind,
			&i.ResourceName,
			&i.Unit,
			&i.UnitPriceUsd,
			&i.EffectiveAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectivePricings = `-- name: ListEffectivePricings :many
SELECT id, resource_kind, resource_name, unit, unit_price_usd, effective_at, expires_at
FROM pricing
WHERE resource_kind = $1
  AND resource_name = $2
  AND effective_at <= $3
  AND (expires_at IS NULL OR expires_at > $3)
ORDER BY effective_at DESC
`

type ListEffectivePricingsParams struct {
	ResourceKind string             `json:"resource_kind"`
	ResourceName string             `json:"resource_name"`
	EffectiveAt  pgtype.Timestamptz `json:"effective_at"`
}

// Returns every pricing row for (resource_kind, resource_name) whose
// effective window covers $3 (occurred_at), across all units. The Cost
// Service picks at most one row per `unit` in Go — the row with the latest
// effective_at wins on collision. Replaces N per-unit GetEffectivePricing
// round-trips with a single scan per event.
//
// Window predicate is right-exclusive on expires_at (a row whose expires_at
// equals occurred_at exactly does NOT match — matches the spec scenario
// "Pricing windows abut exactly at occurred_at").
func (q *Queries) ListEffectivePricings(ctx context.Context, arg ListEffectivePricingsParams) ([]Pricing, error) {
	rows, err := q.db.Query(ctx, listEffectivePricings, arg.ResourceKind, arg.ResourceName, arg.EffectiveAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pricing
	for rows.Next() {
		var i Pricing
		if err := rows.Scan(
			&i.ID,
			&i.ResourceKind,
			&i.ResourceName,
			&i.Unit,
			&i.UnitPriceUsd,
			&i.EffectiveAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
