// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEffectivePricing = `-- name: GetEffectivePricing :one
SELECT id, resource_kind, resource_name, unit, unit_price_usd, effective_at, expires_at
FROM pricing
WHERE resource_kind = $1
  AND resource_name = $2
  AND unit          = $3
  AND effective_at <= $4
  AND (expires_at IS NULL OR expires_at > $4)
ORDER BY effective_at DESC
LIMIT 1
`

type GetEffectivePricingParams struct {
	ResourceKind string             `json:"resource_kind"`
	ResourceName string             `json:"resource_name"`
	Unit         string             `json:"unit"`
	EffectiveAt  pgtype.Timestamptz `json:"effective_at"`
}

// Returns the pricing row in force at $4 for (resource_kind, resource_name,
// unit), or no rows if none. Used by the Cost Service when scoring a
// cost_event at write time.
func (q *Queries) GetEffectivePricing(ctx context.Context, arg GetEffectivePricingParams) (Pricing, error) {
	row := q.db.QueryRow(ctx, getEffectivePricing,
		arg.ResourceKind,
		arg.ResourceName,
		arg.Unit,
		arg.EffectiveAt,
	)
	var i Pricing
	err := row.Scan(
		&i.ID,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Unit,
		&i.UnitPriceUsd,
		&i.EffectiveAt,
		&i.ExpiresAt,
	)
	return i, err
}
