// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Used by the outbox_pending gauge.
	CountOutboxPending(ctx context.Context) (int64, error)
	// Insert a new task and return the row. The caller is responsible for ID
	// generation and for choosing the initial `status` (typically 'pending').
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Insert a new run. The unique idempotency_key lets workers issue
	// INSERT ... ON CONFLICT (idempotency_key) DO NOTHING RETURNING id for the
	// four-branch claim from worker-messaging spec (see add-task-create-api).
	CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (TaskRun, error)
	// Insert a new version. The DB enforces task-level mutex: at most one row
	// with `is_active = true` per task_id, via the unique partial index
	// `one_active_version_per_task`. A second concurrent insert with an active
	// status raises SQLSTATE 23505 with that constraint name; callers translate
	// the error to a 409 envelope (owned by add-task-create-api).
	CreateTaskVersion(ctx context.Context, arg CreateTaskVersionParams) (TaskVersion, error)
	// Returns the pricing row in force at $4 for (resource_kind, resource_name,
	// unit), or no rows if none. Used by the Cost Service when scoring a
	// cost_event at write time.
	GetEffectivePricing(ctx context.Context, arg GetEffectivePricingParams) (Pricing, error)
	GetRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (TaskRun, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	// Task-level totals across all versions. Returns a single row with
	// aggregated values (zeros when no rows match — COALESCE keeps the API
	// caller from special-casing NULLs).
	GetTaskCost(ctx context.Context, taskID pgtype.UUID) (GetTaskCostRow, error)
	GetTaskRunByID(ctx context.Context, id pgtype.UUID) (TaskRun, error)
	GetTaskVersionByID(ctx context.Context, id pgtype.UUID) (TaskVersion, error)
	// One row per version. Returns no rows if the Cost Service hasn't yet
	// upserted anything for the version (treat as "0 across the board").
	GetVersionCost(ctx context.Context, versionID pgtype.UUID) (TaskCost, error)
	// Records a publish failure: bumps attempts and schedules a retry at next_retry_at.
	IncrementOutboxAttempt(ctx context.Context, arg IncrementOutboxAttemptParams) error
	// Idempotent on (run_id, seq). Duplicate inserts from the Realtime Gateway
	// on Worker retries are silently dropped.
	InsertTaskEvent(ctx context.Context, arg InsertTaskEventParams) error
	ListArtifactsByVersion(ctx context.Context, versionID pgtype.UUID) ([]Artifact, error)
	// Pagination for WS gap-fill and HTTP replay: caller passes the highest
	// event id it has already observed. Results are monotonically ordered by
	// id; the (task_id, id) index supports the predicate. Pagination via LIMIT.
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TaskEvent, error)
	// Owner-scoped listing with an optional status filter. Pass NULL for `status`
	// to skip the filter. Newest tasks first; pagination via LIMIT/OFFSET.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	// Returns all versions for a task ordered by version_no ascending so callers
	// can rebuild the tree client-side.
	ListVersionsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskVersion, error)
	// Moves an outbox row to terminal failed state after exhausting retries.
	MarkOutboxFailed(ctx context.Context, id int64) error
	// Marks an outbox row as successfully published.
	MarkOutboxSent(ctx context.Context, id int64) error
	// Returns up to $1 pending rows whose next_retry_at has elapsed (or is unset),
	// ordered by id for stable replay. Used by the Outbox Relayer scan step.
	ScanPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	// The highest-step_seq checkpoint for a run, or zero rows if none. Workers
	// use this on resume to find the resume point.
	SelectLatestCheckpoint(ctx context.Context, runID pgtype.UUID) (TaskCheckpoint, error)
}

var _ Querier = (*Queries)(nil)
