// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Used by the outbox_pending gauge.
	CountOutboxPending(ctx context.Context) (int64, error)
	// Total count of the caller's tasks for offset pagination, using the same
	// owner + optional-status predicate as ListTasks. Pass NULL for `status` to
	// skip the filter.
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	// Insert a new task and return the row. The caller is responsible for ID
	// generation and for choosing the initial `status` (typically 'pending').
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Insert a new run. The unique idempotency_key lets workers issue
	// INSERT ... ON CONFLICT (idempotency_key) DO NOTHING RETURNING id for the
	// four-branch claim from worker-messaging spec (see add-task-create-api).
	CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (TaskRun, error)
	// Insert a new version. The DB enforces task-level mutex: at most one row
	// with `is_active = true` per task_id, via the unique partial index
	// `one_active_version_per_task`. A second concurrent insert with an active
	// status raises SQLSTATE 23505 with that constraint name; callers translate
	// the error to a 409 envelope (owned by add-task-create-api).
	CreateTaskVersion(ctx context.Context, arg CreateTaskVersionParams) (TaskVersion, error)
	// Returns the (at most one) active version row for a task; used by the
	// task-write-api 409 path to enrich the response envelope after the savepoint
	// detects a mutex hit. The unique partial index `one_active_version_per_task`
	// guarantees at most one match.
	GetActiveVersionByTask(ctx context.Context, taskID pgtype.UUID) (TaskVersion, error)
	// Returns the pricing row in force at $4 for (resource_kind, resource_name,
	// unit), or no rows if none. Used by the Cost Service when scoring a
	// cost_event at write time.
	GetEffectivePricing(ctx context.Context, arg GetEffectivePricingParams) (Pricing, error)
	GetRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (TaskRun, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	// Task-level totals across all versions. Returns a single row with
	// aggregated values (zeros when no rows match — COALESCE keeps the API
	// caller from special-casing NULLs).
	GetTaskCost(ctx context.Context, taskID pgtype.UUID) (GetTaskCostRow, error)
	GetTaskRunByID(ctx context.Context, id pgtype.UUID) (TaskRun, error)
	GetTaskVersionByID(ctx context.Context, id pgtype.UUID) (TaskVersion, error)
	// Look up a specific version inside a task. Used to validate that an
	// iterate request's optional `base_version_id` belongs to the path task_id
	// atomically, without round-tripping a separate ownership check.
	GetVersionByTaskAndID(ctx context.Context, arg GetVersionByTaskAndIDParams) (TaskVersion, error)
	// One row per version. Returns no rows if the Cost Service hasn't yet
	// upserted anything for the version (treat as "0 across the board").
	GetVersionCost(ctx context.Context, versionID pgtype.UUID) (TaskCost, error)
	// Records a publish failure: bumps attempts and schedules a retry at next_retry_at.
	IncrementOutboxAttempt(ctx context.Context, arg IncrementOutboxAttemptParams) error
	// Append a new outbox row inside the same transaction as the business write
	// it triggers. Returns id/status/created_at so the caller can correlate with
	// the publisher's metric output. Used by the task-write-api flow to enqueue
	// `execute.<task_type>.<lane>` messages.
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) (InsertOutboxRow, error)
	// Idempotent on (run_id, seq). Duplicate inserts from the Realtime Gateway
	// on Worker retries are silently dropped.
	InsertTaskEvent(ctx context.Context, arg InsertTaskEventParams) error
	ListArtifactsByVersion(ctx context.Context, versionID pgtype.UUID) ([]Artifact, error)
	// Pagination for WS gap-fill and HTTP replay: caller passes the highest
	// event id it has already observed. Results are monotonically ordered by
	// id; the (task_id, id) index supports the predicate. Pagination via LIMIT.
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TaskEvent, error)
	// All runs for a version, oldest attempt first, for the version-detail view
	// (retry history). The (version_id, attempt_no) unique constraint backs the
	// ordering.
	ListRunsByVersion(ctx context.Context, versionID pgtype.UUID) ([]TaskRun, error)
	// Batched per-task cost totals for the task list, avoiding an N+1 of
	// GetTaskCost per row. Returns one row per task_id that has any task_costs
	// rows; tasks absent from the result are zero-filled by the caller.
	ListTaskCostsByTasks(ctx context.Context, taskIds []pgtype.UUID) ([]ListTaskCostsByTasksRow, error)
	// Owner-scoped listing with an optional status filter. Pass NULL for `status`
	// to skip the filter. Newest tasks first; pagination via LIMIT/OFFSET.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	// All per-version cost rows for a task, fetched once for the whole version
	// tree (avoids a per-node GetVersionCost N+1). Versions without a row are
	// zero-filled by the caller. Covered by the task_costs (task_id) index.
	ListVersionCostsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskCost, error)
	// Version-scoped event backfill for the HTTP replay endpoint. Anchors on the
	// existing (task_id, id) index (task_id equality + id range) and filters
	// version_id as a residual predicate, so no new index is required. The caller
	// passes the task_id resolved from the version plus the highest id seen.
	ListVersionEventsAfter(ctx context.Context, arg ListVersionEventsAfterParams) ([]TaskEvent, error)
	// Returns all versions for a task ordered by version_no ascending so callers
	// can rebuild the tree client-side.
	ListVersionsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskVersion, error)
	// Acquires a row-level lock on a task and returns its id/status/current_version.
	// Used by the iterate path so concurrent requests against the same task
	// serialise behind one another inside the transaction.
	LockTaskRow(ctx context.Context, id pgtype.UUID) (LockTaskRowRow, error)
	// Moves an outbox row to terminal failed state after exhausting retries.
	MarkOutboxFailed(ctx context.Context, id int64) error
	// Marks an outbox row as successfully published.
	MarkOutboxSent(ctx context.Context, id int64) error
	// Highest version_no observed for a task, 0 when none exist. Used by iterate
	// to assign the new version_no (max + 1).
	MaxVersionNoForTask(ctx context.Context, taskID pgtype.UUID) (int32, error)
	// Returns up to $1 pending rows whose next_retry_at has elapsed (or is unset),
	// ordered by id for stable replay. Used by the Outbox Relayer scan step.
	ScanPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	// The highest-step_seq checkpoint for a run, or zero rows if none. Workers
	// use this on resume to find the resume point.
	SelectLatestCheckpoint(ctx context.Context, runID pgtype.UUID) (TaskCheckpoint, error)
	// Points `tasks.current_version` at the new version and stamps the task back
	// to `pending`. Called by the iterate transaction after `createActiveVersion`
	// succeeds.
	UpdateTaskCurrentVersion(ctx context.Context, arg UpdateTaskCurrentVersionParams) error
	// Event-ingest state-machine CAS (add-event-ingest-status-sync). Only the
	// task's current (active) version may drive tasks.status, so the update is
	// gated on current_version = $3 — a stale event for a superseded version is
	// a no-op. Same terminal + real-transition guards as UpdateVersionStatus.
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (int64, error)
	// Event-ingest state-machine CAS (add-event-ingest-status-sync). The WHERE
	// clause carries two guards so the update is safe under at-least-once,
	// out-of-order delivery:
	//   * terminal guard: a version already in a terminal state is never moved;
	//   * real-transition guard (IS DISTINCT FROM): a redelivered same-status
	//     event affects 0 rows, so the caller's transition metric is accurate.
	// Setting a terminal status flips the generated is_active column to false
	// automatically, freeing the one_active_version_per_task index slot.
	UpdateVersionStatus(ctx context.Context, arg UpdateVersionStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
