// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Used by the outbox_pending gauge.
	CountOutboxPending(ctx context.Context) (int64, error)
	// Total count of the caller's tasks for offset pagination, using the same
	// owner + optional-status predicate as ListTasks. Pass NULL for `status` to
	// skip the filter.
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	// Insert a new task and return the row. The caller is responsible for ID
	// generation and for choosing the initial `status` (typically 'pending').
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Insert a new run. The unique idempotency_key lets workers issue
	// INSERT ... ON CONFLICT (idempotency_key) DO NOTHING RETURNING id for the
	// four-branch claim from worker-messaging spec (see add-task-create-api).
	CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (TaskRun, error)
	// Insert a new version. The DB enforces task-level mutex: at most one row
	// with `is_active = true` per task_id, via the unique partial index
	// `one_active_version_per_task`. A second concurrent insert with an active
	// status raises SQLSTATE 23505 with that constraint name; callers translate
	// the error to a 409 envelope (owned by add-task-create-api).
	CreateTaskVersion(ctx context.Context, arg CreateTaskVersionParams) (TaskVersion, error)
	// Resolves the latest task_runs.id for the task's current version
	// (add-task-control-api). Returns no rows when current_version is NULL
	// or no attempts have been claimed yet (pre-claim state — the caller
	// writes the outbox row with run_id = null).
	//
	// "Latest" = highest attempt_no, NOT a status filter. A terminal run
	// (e.g. succeeded) may surface here; the worker is the authoritative
	// "is this run currently active in my process" filter. Reviewer S10.
	GetActiveRunIDForTask(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Returns the (at most one) active version row for a task; used by the
	// task-write-api 409 path to enrich the response envelope after the savepoint
	// detects a mutex hit. The unique partial index `one_active_version_per_task`
	// guarantees at most one match.
	GetActiveVersionByTask(ctx context.Context, taskID pgtype.UUID) (TaskVersion, error)
	// Resolves an artifact's storage key + owning identity in one round-trip
	// (artifacts → task_versions → tasks). Selects only what the presign endpoint
	// needs; id/kind/created_at are intentionally omitted so unused columns never
	// reach DTO assembly (design D4 — defends the never-serialize-oss_key invariant).
	GetArtifactWithOwner(ctx context.Context, id pgtype.UUID) (GetArtifactWithOwnerRow, error)
	// Returns the pricing row in force at $4 for (resource_kind, resource_name,
	// unit), or no rows if none. Used by the Cost Service when scoring a
	// cost_event at write time.
	GetEffectivePricing(ctx context.Context, arg GetEffectivePricingParams) (Pricing, error)
	GetRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (TaskRun, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	// Task-level totals across all versions. Returns a single row with
	// aggregated values (zeros when no rows match — COALESCE keeps the API
	// caller from special-casing NULLs).
	GetTaskCost(ctx context.Context, taskID pgtype.UUID) (GetTaskCostRow, error)
	// Task-level totals scoped to an owner. Drives FROM tasks (not task_costs)
	// and LEFT JOINs the cost rows so an owned-but-empty task — one with no
	// versions / no settled events yet — still returns a 1-row zero-aggregate.
	// An unknown OR unowned task_id returns no rows; the caller maps pgx.ErrNoRows
	// to ErrTaskNotFound (identical 404 regardless of cause). GROUP BY t.id is
	// load-bearing: without it the aggregate would always return 1 row with zero
	// sums regardless of the WHERE — breaking the owner check.
	GetTaskCostWithOwner(ctx context.Context, arg GetTaskCostWithOwnerParams) (GetTaskCostWithOwnerRow, error)
	GetTaskRunByID(ctx context.Context, id pgtype.UUID) (TaskRun, error)
	GetTaskVersionByID(ctx context.Context, id pgtype.UUID) (TaskVersion, error)
	// Credential lookup for POST /auth/login. Matched case-insensitively against
	// the users_email_lower_key index; the caller passes an already-lowercased
	// email but lower($1) keeps the predicate aligned with the index regardless.
	// Returns no rows for an unknown email; the repository maps pgx.ErrNoRows to
	// identity.ErrUserNotFound (collapsed to ErrInvalidCredentials by the verifier).
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	// Look up a specific version inside a task. Used to validate that an
	// iterate request's optional `base_version_id` belongs to the path task_id
	// atomically, without round-tripping a separate ownership check.
	GetVersionByTaskAndID(ctx context.Context, arg GetVersionByTaskAndIDParams) (TaskVersion, error)
	// One row per version. Returns no rows if the Cost Service hasn't yet
	// upserted anything for the version (treat as "0 across the board").
	GetVersionCost(ctx context.Context, versionID pgtype.UUID) (TaskCost, error)
	// Single-version cost lookup with owner check + owning task_id for
	// deep-linking. Drives FROM task_versions, JOIN tasks for the owner
	// predicate, LEFT JOIN task_costs so versions with no settled events
	// still return a row (cost columns NULL → mapper zero-fills, updated_at
	// NULL becomes null in JSON). Unknown / unowned returns no rows;
	// caller maps to ErrVersionNotFound.
	GetVersionCostWithOwner(ctx context.Context, arg GetVersionCostWithOwnerParams) (GetVersionCostWithOwnerRow, error)
	// Narrow lookup returning just the version's owning task_id. Used by the
	// Cost Service to verify a worker-supplied (task_id, version_id) before
	// the task_costs UPSERT, enforcing task-cost-data-model §"Task Costs
	// task_id is Immutable Per version_id". Returns no rows if version_id is
	// unknown (caller treats as DLQ-permanent).
	GetVersionOwnerTaskID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Caller-scoped grouped rollups for /me/cost. Split into three queries
	// (instead of one with `CASE sqlc.arg('group_by')`) because sqlc infers
	// the CASE-expression result as `interface{}` — design D5 contingency
	// triggered. Each query is otherwise identical in shape to SumOwnerCosts
	// and emits a stable `string` key. ORDER BY key ASC keeps client
	// rendering deterministic without a second sort.
	// Day bucket; the PG16+ three-arg date_trunc pins UTC so the boundary
	// doesn't drift with the connection's session TimeZone.
	GroupOwnerCostsByDay(ctx context.Context, arg GroupOwnerCostsByDayParams) ([]GroupOwnerCostsByDayRow, error)
	// Group by model. Llm events bucket by resource_name; tool/compute events
	// collapse into a single 'other' bucket so the amount_usd sum still
	// reconciles with SumOwnerCosts.
	GroupOwnerCostsByModel(ctx context.Context, arg GroupOwnerCostsByModelParams) ([]GroupOwnerCostsByModelRow, error)
	// Group by tasks.task_type. NULL is impossible (task_type is NOT NULL) so
	// no COALESCE needed.
	GroupOwnerCostsByTaskType(ctx context.Context, arg GroupOwnerCostsByTaskTypeParams) ([]GroupOwnerCostsByTaskTypeRow, error)
	// Records a publish failure: bumps attempts and schedules a retry at next_retry_at.
	IncrementOutboxAttempt(ctx context.Context, arg IncrementOutboxAttemptParams) error
	// Idempotent insert keyed on (run_id, kind, seq) — the uniqueness boundary
	// after migration 0004_cost_events_kind_unique (matches the Worker's
	// per-(run_id, kind) seq namespace per worker-messaging §"Cost Event
	// Publisher"). Returns the inserted row's quantity / amount fields so the
	// caller can drive the task_costs UPSERT in the same transaction. On
	// duplicate delivery the RETURNING set is empty (caller treats pgx.ErrNoRows
	// as "duplicate, skip aggregate UPSERT").
	InsertCostEvent(ctx context.Context, arg InsertCostEventParams) (InsertCostEventRow, error)
	// Append a new outbox row inside the same transaction as the business write
	// it triggers. Returns id/status/created_at so the caller can correlate with
	// the publisher's metric output.
	//
	// `exchange` was added by `add-task-control-api` so each row carries its
	// own destination exchange (the Relayer no longer keeps a constant).
	// Existing callers (createActiveVersion in domain/task/service.go) pass
	// `'task.exchange'` explicitly; control writers pass `'task.control'`.
	InsertOutbox(ctx context.Context, arg InsertOutboxParams) (InsertOutboxRow, error)
	// Idempotent on (run_id, seq). Duplicate inserts from the Realtime Gateway
	// on Worker retries are silently dropped.
	InsertTaskEvent(ctx context.Context, arg InsertTaskEventParams) error
	ListArtifactsByVersion(ctx context.Context, versionID pgtype.UUID) ([]Artifact, error)
	// All pricing rows in force at now() — the source for GET /api/v1/pricing.
	// Owner-agnostic; every authenticated caller receives the same body.
	// Ordering is stable so JSON byte-identity across callers holds (S15 test).
	ListCurrentPricing(ctx context.Context) ([]Pricing, error)
	// Returns every pricing row for (resource_kind, resource_name) whose
	// effective window covers $3 (occurred_at), across all units. The Cost
	// Service picks at most one row per `unit` in Go — the row with the latest
	// effective_at wins on collision. Replaces N per-unit GetEffectivePricing
	// round-trips with a single scan per event.
	//
	// Window predicate is right-exclusive on expires_at (a row whose expires_at
	// equals occurred_at exactly does NOT match — matches the spec scenario
	// "Pricing windows abut exactly at occurred_at").
	ListEffectivePricings(ctx context.Context, arg ListEffectivePricingsParams) ([]Pricing, error)
	// Pagination for WS gap-fill and HTTP replay: caller passes the highest
	// event id it has already observed. Results are monotonically ordered by
	// id; the (task_id, id) index supports the predicate. Pagination via LIMIT.
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TaskEvent, error)
	// All runs for a version, oldest attempt first, for the version-detail view
	// (retry history). The (version_id, attempt_no) unique constraint backs the
	// ordering.
	ListRunsByVersion(ctx context.Context, versionID pgtype.UUID) ([]TaskRun, error)
	// Batched per-task cost totals for the task list, avoiding an N+1 of
	// GetTaskCost per row. Returns one row per task_id that has any task_costs
	// rows; tasks absent from the result are zero-filled by the caller.
	ListTaskCostsByTasks(ctx context.Context, taskIds []pgtype.UUID) ([]ListTaskCostsByTasksRow, error)
	// Owner-scoped listing with an optional status filter. Pass NULL for `status`
	// to skip the filter. Newest tasks first; pagination via LIMIT/OFFSET.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	// All per-version cost rows for a task, fetched once for the whole version
	// tree (avoids a per-node GetVersionCost N+1). Versions without a row are
	// zero-filled by the caller. Covered by the task_costs (task_id) index.
	ListVersionCostsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskCost, error)
	// Per-version breakdown for /tasks/{id}/cost. Drives FROM task_versions
	// (LEFT JOIN task_costs) so a version whose Cost Service has nothing to
	// UPSERT yet still appears in the breakdown with the cost columns as NULL
	// (the caller zero-fills). Ownership predicate goes through tasks. Orders
	// by version_no ASC so the breakdown renders chronologically without a
	// second sort on the client.
	ListVersionCostsForTask(ctx context.Context, arg ListVersionCostsForTaskParams) ([]ListVersionCostsForTaskRow, error)
	// Version-scoped event backfill for the HTTP replay endpoint. Anchors on the
	// existing (task_id, id) index (task_id equality + id range) and filters
	// version_id as a residual predicate, so no new index is required. The caller
	// passes the task_id resolved from the version plus the highest id seen.
	ListVersionEventsAfter(ctx context.Context, arg ListVersionEventsAfterParams) ([]TaskEvent, error)
	// Returns all versions for a task ordered by version_no ascending so callers
	// can rebuild the tree client-side.
	ListVersionsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskVersion, error)
	// Acquires a row-level lock AND verifies ownership in one round-trip
	// (add-task-control-api). Concurrent control requests for the same task
	// serialise on this lock; the second handler observes the first's tx
	// outcome before reading task.status. Owner predicate is inline so
	// unknown OR unowned tasks return no rows — the caller maps
	// pgx.ErrNoRows to ErrTaskNotFound for the identical 404 regardless of
	// cause (mirrors task-read-api / task-cost-api).
	LockTaskForControl(ctx context.Context, arg LockTaskForControlParams) (LockTaskForControlRow, error)
	// Acquires a row-level lock on a task and returns its id/status/current_version.
	// Used by the iterate path so concurrent requests against the same task
	// serialise behind one another inside the transaction.
	LockTaskRow(ctx context.Context, id pgtype.UUID) (LockTaskRowRow, error)
	// Moves an outbox row to terminal failed state after exhausting retries.
	MarkOutboxFailed(ctx context.Context, id int64) error
	// Marks an outbox row as successfully published.
	MarkOutboxSent(ctx context.Context, id int64) error
	// Highest version_no observed for a task, 0 when none exist. Used by iterate
	// to assign the new version_no (max + 1).
	MaxVersionNoForTask(ctx context.Context, taskID pgtype.UUID) (int32, error)
	// Returns up to $1 pending rows whose next_retry_at has elapsed (or is unset),
	// ordered by id for stable replay. Used by the Outbox Relayer scan step.
	ScanPendingOutbox(ctx context.Context, limit int32) ([]Outbox, error)
	// The highest-step_seq checkpoint for a run, or zero rows if none. Workers
	// use this on resume to find the resume point.
	SelectLatestCheckpoint(ctx context.Context, runID pgtype.UUID) (TaskCheckpoint, error)
	// Caller-scoped totals for /me/cost (no group_by branch). Aggregates
	// cost_events directly so the time filter applies to occurred_at — settle-
	// time would corrupt buckets when a backfill lands. Per-column FILTER
	// clauses mirror the cost-ingest per-kind mapping so the resulting
	// CostSummary shape matches task_costs' semantics:
	//   * tool_calls bumps only for kind='tool' (NULL→1 default per worker contract)
	//   * wall_time_ms bumps for kind IN ('llm','tool') (compute events have
	//     their own aggregate, but CostSummary doesn't surface compute_seconds)
	//   * token columns are plain SUM (NULL contributes 0)
	// The inner JOIN to tasks is the owner gate AND defense-in-depth against
	// orphaned cost_events.task_id rows (no FK on that column).
	SumOwnerCosts(ctx context.Context, arg SumOwnerCostsParams) (SumOwnerCostsRow, error)
	// Points `tasks.current_version` at the new version and stamps the task back
	// to `pending`. Called by the iterate transaction after `createActiveVersion`
	// succeeds.
	UpdateTaskCurrentVersion(ctx context.Context, arg UpdateTaskCurrentVersionParams) error
	// Event-ingest state-machine CAS (add-event-ingest-status-sync). Only the
	// task's current (active) version may drive tasks.status, so the update is
	// gated on current_version = $3 — a stale event for a superseded version is
	// a no-op. Same terminal + real-transition guards as UpdateVersionStatus.
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (int64, error)
	// Event-ingest state-machine CAS (add-event-ingest-status-sync). The WHERE
	// clause carries two guards so the update is safe under at-least-once,
	// out-of-order delivery:
	//   * terminal guard: a version already in a terminal state is never moved;
	//   * real-transition guard (IS DISTINCT FROM): a redelivered same-status
	//     event affects 0 rows, so the caller's transition metric is accurate.
	// Setting a terminal status flips the generated is_active column to false
	// automatically, freeing the one_active_version_per_task index slot.
	UpdateVersionStatus(ctx context.Context, arg UpdateVersionStatusParams) (int64, error)
	// Idempotent dev-seed of the tenant. Keyed on id so repeated boots converge;
	// the name is left untouched on conflict (the seed only guarantees existence).
	UpsertTenant(ctx context.Context, arg UpsertTenantParams) error
	// Idempotent dev-seed of the user. Keyed on id so repeated boots converge and a
	// changed configured password refreshes the stored hash. password_hash holds a
	// bcrypt digest — never the plaintext.
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
	// Sole writer to task_costs (task-cost-data-model §"Task Costs Aggregation
	// Table"). Per-event aggregate increment; caller pre-resolves NULL→0 and
	// per-kind column gating per spec §"Aggregate Increment Mapping Per Kind".
	//
	// task_id is deliberately ABSENT from DO UPDATE SET — task-cost-data-model
	// §"Task Costs task_id is Immutable Per version_id" requires that a
	// version_id's task ownership never migrate via the UPSERT. The settler
	// pre-verifies via task_versions and DLQs on mismatch, so by the time we
	// get here the supplied task_id is authoritative for an INSERT but
	// redundant on UPDATE.
	UpsertVersionCost(ctx context.Context, arg UpsertVersionCostParams) error
}

var _ Querier = (*Queries)(nil)
