// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskRun = `-- name: CreateTaskRun :one
INSERT INTO task_runs (
    id, version_id, attempt_no, worker_run_id, status, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, version_id, attempt_no, worker_run_id, status, started_at, ended_at, last_heartbeat, error, idempotency_key
`

type CreateTaskRunParams struct {
	ID             pgtype.UUID `json:"id"`
	VersionID      pgtype.UUID `json:"version_id"`
	AttemptNo      int32       `json:"attempt_no"`
	WorkerRunID    pgtype.UUID `json:"worker_run_id"`
	Status         string      `json:"status"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// Insert a new run. The unique idempotency_key lets workers issue
// INSERT ... ON CONFLICT (idempotency_key) DO NOTHING RETURNING id for the
// four-branch claim from worker-messaging spec (see add-task-create-api).
func (q *Queries) CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (TaskRun, error) {
	row := q.db.QueryRow(ctx, createTaskRun,
		arg.ID,
		arg.VersionID,
		arg.AttemptNo,
		arg.WorkerRunID,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i TaskRun
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.AttemptNo,
		&i.WorkerRunID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastHeartbeat,
		&i.Error,
		&i.IdempotencyKey,
	)
	return i, err
}

const getActiveRunIDForTask = `-- name: GetActiveRunIDForTask :one
SELECT r.id
FROM task_runs r
JOIN tasks t ON t.current_version = r.version_id
WHERE t.id = $1
ORDER BY r.attempt_no DESC
LIMIT 1
`

// Resolves the latest task_runs.id for the task's current version
// (add-task-control-api). Returns no rows when current_version is NULL
// or no attempts have been claimed yet (pre-claim state — the caller
// writes the outbox row with run_id = null).
//
// "Latest" = highest attempt_no, NOT a status filter. A terminal run
// (e.g. succeeded) may surface here; the worker is the authoritative
// "is this run currently active in my process" filter. Reviewer S10.
func (q *Queries) GetActiveRunIDForTask(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveRunIDForTask, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getRunByIdempotencyKey = `-- name: GetRunByIdempotencyKey :one
SELECT id, version_id, attempt_no, worker_run_id, status, started_at, ended_at, last_heartbeat, error, idempotency_key
FROM task_runs
WHERE idempotency_key = $1
`

func (q *Queries) GetRunByIdempotencyKey(ctx context.Context, idempotencyKey string) (TaskRun, error) {
	row := q.db.QueryRow(ctx, getRunByIdempotencyKey, idempotencyKey)
	var i TaskRun
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.AttemptNo,
		&i.WorkerRunID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastHeartbeat,
		&i.Error,
		&i.IdempotencyKey,
	)
	return i, err
}

const getTaskRunByID = `-- name: GetTaskRunByID :one
SELECT id, version_id, attempt_no, worker_run_id, status, started_at, ended_at, last_heartbeat, error, idempotency_key
FROM task_runs
WHERE id = $1
`

func (q *Queries) GetTaskRunByID(ctx context.Context, id pgtype.UUID) (TaskRun, error) {
	row := q.db.QueryRow(ctx, getTaskRunByID, id)
	var i TaskRun
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.AttemptNo,
		&i.WorkerRunID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.LastHeartbeat,
		&i.Error,
		&i.IdempotencyKey,
	)
	return i, err
}

const listRunsByVersion = `-- name: ListRunsByVersion :many
SELECT id, version_id, attempt_no, worker_run_id, status, started_at, ended_at, last_heartbeat, error, idempotency_key
FROM task_runs
WHERE version_id = $1
ORDER BY attempt_no ASC
`

// All runs for a version, oldest attempt first, for the version-detail view
// (retry history). The (version_id, attempt_no) unique constraint backs the
// ordering.
func (q *Queries) ListRunsByVersion(ctx context.Context, versionID pgtype.UUID) ([]TaskRun, error) {
	rows, err := q.db.Query(ctx, listRunsByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRun
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.AttemptNo,
			&i.WorkerRunID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.LastHeartbeat,
			&i.Error,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
