// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_versions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskVersion = `-- name: CreateTaskVersion :one
INSERT INTO task_versions (
    id, task_id, parent_id, version_no, prompt, params, status, artifact_root
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
`

type CreateTaskVersionParams struct {
	ID           pgtype.UUID `json:"id"`
	TaskID       pgtype.UUID `json:"task_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	VersionNo    int32       `json:"version_no"`
	Prompt       string      `json:"prompt"`
	Params       []byte      `json:"params"`
	Status       string      `json:"status"`
	ArtifactRoot *string     `json:"artifact_root"`
}

// Insert a new version. The DB enforces task-level mutex: at most one row
// with `is_active = true` per task_id, via the unique partial index
// `one_active_version_per_task`. A second concurrent insert with an active
// status raises SQLSTATE 23505 with that constraint name; callers translate
// the error to a 409 envelope (owned by add-task-create-api).
func (q *Queries) CreateTaskVersion(ctx context.Context, arg CreateTaskVersionParams) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, createTaskVersion,
		arg.ID,
		arg.TaskID,
		arg.ParentID,
		arg.VersionNo,
		arg.Prompt,
		arg.Params,
		arg.Status,
		arg.ArtifactRoot,
	)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ParentID,
		&i.VersionNo,
		&i.Prompt,
		&i.Params,
		&i.Status,
		&i.IsActive,
		&i.ArtifactRoot,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskVersionByID = `-- name: GetTaskVersionByID :one
SELECT id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
FROM task_versions
WHERE id = $1
`

func (q *Queries) GetTaskVersionByID(ctx context.Context, id pgtype.UUID) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, getTaskVersionByID, id)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ParentID,
		&i.VersionNo,
		&i.Prompt,
		&i.Params,
		&i.Status,
		&i.IsActive,
		&i.ArtifactRoot,
		&i.CreatedAt,
	)
	return i, err
}

const listVersionsByTask = `-- name: ListVersionsByTask :many
SELECT id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
FROM task_versions
WHERE task_id = $1
ORDER BY version_no ASC
`

// Returns all versions for a task ordered by version_no ascending so callers
// can rebuild the tree client-side.
func (q *Queries) ListVersionsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskVersion
	for rows.Next() {
		var i TaskVersion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ParentID,
			&i.VersionNo,
			&i.Prompt,
			&i.Params,
			&i.Status,
			&i.IsActive,
			&i.ArtifactRoot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
