// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_versions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskVersion = `-- name: CreateTaskVersion :one
INSERT INTO task_versions (
    id, task_id, parent_id, version_no, prompt, params, status, artifact_root
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
`

type CreateTaskVersionParams struct {
	ID           pgtype.UUID `json:"id"`
	TaskID       pgtype.UUID `json:"task_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	VersionNo    int32       `json:"version_no"`
	Prompt       string      `json:"prompt"`
	Params       []byte      `json:"params"`
	Status       string      `json:"status"`
	ArtifactRoot *string     `json:"artifact_root"`
}

// Insert a new version. The DB enforces task-level mutex: at most one row
// with `is_active = true` per task_id, via the unique partial index
// `one_active_version_per_task`. A second concurrent insert with an active
// status raises SQLSTATE 23505 with that constraint name; callers translate
// the error to a 409 envelope (owned by add-task-create-api).
func (q *Queries) CreateTaskVersion(ctx context.Context, arg CreateTaskVersionParams) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, createTaskVersion,
		arg.ID,
		arg.TaskID,
		arg.ParentID,
		arg.VersionNo,
		arg.Prompt,
		arg.Params,
		arg.Status,
		arg.ArtifactRoot,
	)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ParentID,
		&i.VersionNo,
		&i.Prompt,
		&i.Params,
		&i.Status,
		&i.IsActive,
		&i.ArtifactRoot,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveVersionByTask = `-- name: GetActiveVersionByTask :one
SELECT id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
FROM task_versions
WHERE task_id = $1 AND is_active
ORDER BY version_no DESC
LIMIT 1
`

// Returns the (at most one) active version row for a task; used by the
// task-write-api 409 path to enrich the response envelope after the savepoint
// detects a mutex hit. The unique partial index `one_active_version_per_task`
// guarantees at most one match.
func (q *Queries) GetActiveVersionByTask(ctx context.Context, taskID pgtype.UUID) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, getActiveVersionByTask, taskID)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ParentID,
		&i.VersionNo,
		&i.Prompt,
		&i.Params,
		&i.Status,
		&i.IsActive,
		&i.ArtifactRoot,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskVersionByID = `-- name: GetTaskVersionByID :one
SELECT id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
FROM task_versions
WHERE id = $1
`

func (q *Queries) GetTaskVersionByID(ctx context.Context, id pgtype.UUID) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, getTaskVersionByID, id)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ParentID,
		&i.VersionNo,
		&i.Prompt,
		&i.Params,
		&i.Status,
		&i.IsActive,
		&i.ArtifactRoot,
		&i.CreatedAt,
	)
	return i, err
}

const getVersionByTaskAndID = `-- name: GetVersionByTaskAndID :one
SELECT id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
FROM task_versions
WHERE id = $1 AND task_id = $2
`

type GetVersionByTaskAndIDParams struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

// Look up a specific version inside a task. Used to validate that an
// iterate request's optional `base_version_id` belongs to the path task_id
// atomically, without round-tripping a separate ownership check.
func (q *Queries) GetVersionByTaskAndID(ctx context.Context, arg GetVersionByTaskAndIDParams) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByTaskAndID, arg.ID, arg.TaskID)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ParentID,
		&i.VersionNo,
		&i.Prompt,
		&i.Params,
		&i.Status,
		&i.IsActive,
		&i.ArtifactRoot,
		&i.CreatedAt,
	)
	return i, err
}

const listVersionsByTask = `-- name: ListVersionsByTask :many
SELECT id, task_id, parent_id, version_no, prompt, params, status, is_active, artifact_root, created_at
FROM task_versions
WHERE task_id = $1
ORDER BY version_no ASC
`

// Returns all versions for a task ordered by version_no ascending so callers
// can rebuild the tree client-side.
func (q *Queries) ListVersionsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskVersion
	for rows.Next() {
		var i TaskVersion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ParentID,
			&i.VersionNo,
			&i.Prompt,
			&i.Params,
			&i.Status,
			&i.IsActive,
			&i.ArtifactRoot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxVersionNoForTask = `-- name: MaxVersionNoForTask :one
SELECT COALESCE(MAX(version_no), 0)::int AS max_version_no
FROM task_versions
WHERE task_id = $1
`

// Highest version_no observed for a task, 0 when none exist. Used by iterate
// to assign the new version_no (max + 1).
func (q *Queries) MaxVersionNoForTask(ctx context.Context, taskID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxVersionNoForTask, taskID)
	var max_version_no int32
	err := row.Scan(&max_version_no)
	return max_version_no, err
}

const updateVersionStatus = `-- name: UpdateVersionStatus :execrows
UPDATE task_versions
SET status = $2
WHERE id = $1
  AND status NOT IN ('succeeded', 'failed', 'cancelled')
  AND status IS DISTINCT FROM $2
`

type UpdateVersionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Event-ingest state-machine CAS (add-event-ingest-status-sync). The WHERE
// clause carries two guards so the update is safe under at-least-once,
// out-of-order delivery:
//   - terminal guard: a version already in a terminal state is never moved;
//   - real-transition guard (IS DISTINCT FROM): a redelivered same-status
//     event affects 0 rows, so the caller's transition metric is accurate.
//
// Setting a terminal status flips the generated is_active column to false
// automatically, freeing the one_active_version_per_task index slot.
func (q *Queries) UpdateVersionStatus(ctx context.Context, arg UpdateVersionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVersionStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
