// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_costs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskCost = `-- name: GetTaskCost :one
SELECT
    $1::uuid                                                       AS task_id,
    COALESCE(SUM(input_tokens), 0)::bigint                                          AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint                                         AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::bigint                                         AS cached_tokens,
    COALESCE(SUM(tool_calls), 0)::int                                               AS tool_calls,
    COALESCE(SUM(wall_time_ms), 0)::bigint                                          AS wall_time_ms,
    COALESCE(SUM(compute_seconds), 0)::bigint                                       AS compute_seconds,
    COALESCE(SUM(amount_usd), 0)::numeric                                           AS amount_usd
FROM task_costs
WHERE task_id = $1
`

type GetTaskCostRow struct {
	TaskID         pgtype.UUID    `json:"task_id"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	CachedTokens   int64          `json:"cached_tokens"`
	ToolCalls      int32          `json:"tool_calls"`
	WallTimeMs     int64          `json:"wall_time_ms"`
	ComputeSeconds int64          `json:"compute_seconds"`
	AmountUsd      pgtype.Numeric `json:"amount_usd"`
}

// Task-level totals across all versions. Returns a single row with
// aggregated values (zeros when no rows match — COALESCE keeps the API
// caller from special-casing NULLs).
func (q *Queries) GetTaskCost(ctx context.Context, taskID pgtype.UUID) (GetTaskCostRow, error) {
	row := q.db.QueryRow(ctx, getTaskCost, taskID)
	var i GetTaskCostRow
	err := row.Scan(
		&i.TaskID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.ToolCalls,
		&i.WallTimeMs,
		&i.ComputeSeconds,
		&i.AmountUsd,
	)
	return i, err
}

const getVersionCost = `-- name: GetVersionCost :one
SELECT version_id, task_id, input_tokens, output_tokens, cached_tokens, tool_calls, wall_time_ms, compute_seconds, amount_usd, updated_at
FROM task_costs
WHERE version_id = $1
`

// One row per version. Returns no rows if the Cost Service hasn't yet
// upserted anything for the version (treat as "0 across the board").
func (q *Queries) GetVersionCost(ctx context.Context, versionID pgtype.UUID) (TaskCost, error) {
	row := q.db.QueryRow(ctx, getVersionCost, versionID)
	var i TaskCost
	err := row.Scan(
		&i.VersionID,
		&i.TaskID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.ToolCalls,
		&i.WallTimeMs,
		&i.ComputeSeconds,
		&i.AmountUsd,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskCostsByTasks = `-- name: ListTaskCostsByTasks :many
SELECT
    task_id,
    COALESCE(SUM(input_tokens), 0)::bigint     AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint    AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::bigint     AS cached_tokens,
    COALESCE(SUM(tool_calls), 0)::int           AS tool_calls,
    COALESCE(SUM(wall_time_ms), 0)::bigint       AS wall_time_ms,
    COALESCE(SUM(compute_seconds), 0)::bigint    AS compute_seconds,
    COALESCE(SUM(amount_usd), 0)::numeric        AS amount_usd
FROM task_costs
WHERE task_id = ANY($1::uuid[])
GROUP BY task_id
`

type ListTaskCostsByTasksRow struct {
	TaskID         pgtype.UUID    `json:"task_id"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	CachedTokens   int64          `json:"cached_tokens"`
	ToolCalls      int32          `json:"tool_calls"`
	WallTimeMs     int64          `json:"wall_time_ms"`
	ComputeSeconds int64          `json:"compute_seconds"`
	AmountUsd      pgtype.Numeric `json:"amount_usd"`
}

// Batched per-task cost totals for the task list, avoiding an N+1 of
// GetTaskCost per row. Returns one row per task_id that has any task_costs
// rows; tasks absent from the result are zero-filled by the caller.
func (q *Queries) ListTaskCostsByTasks(ctx context.Context, taskIds []pgtype.UUID) ([]ListTaskCostsByTasksRow, error) {
	rows, err := q.db.Query(ctx, listTaskCostsByTasks, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCostsByTasksRow
	for rows.Next() {
		var i ListTaskCostsByTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.ToolCalls,
			&i.WallTimeMs,
			&i.ComputeSeconds,
			&i.AmountUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionCostsByTask = `-- name: ListVersionCostsByTask :many
SELECT version_id, task_id, input_tokens, output_tokens, cached_tokens, tool_calls, wall_time_ms, compute_seconds, amount_usd, updated_at
FROM task_costs
WHERE task_id = $1
`

// All per-version cost rows for a task, fetched once for the whole version
// tree (avoids a per-node GetVersionCost N+1). Versions without a row are
// zero-filled by the caller. Covered by the task_costs (task_id) index.
func (q *Queries) ListVersionCostsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskCost, error) {
	rows, err := q.db.Query(ctx, listVersionCostsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCost
	for rows.Next() {
		var i TaskCost
		if err := rows.Scan(
			&i.VersionID,
			&i.TaskID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.ToolCalls,
			&i.WallTimeMs,
			&i.ComputeSeconds,
			&i.AmountUsd,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVersionCost = `-- name: UpsertVersionCost :exec
INSERT INTO task_costs (
    version_id, task_id,
    input_tokens, output_tokens, cached_tokens,
    tool_calls, wall_time_ms, compute_seconds, amount_usd
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (version_id) DO UPDATE SET
    input_tokens    = task_costs.input_tokens    + EXCLUDED.input_tokens,
    output_tokens   = task_costs.output_tokens   + EXCLUDED.output_tokens,
    cached_tokens   = task_costs.cached_tokens   + EXCLUDED.cached_tokens,
    tool_calls      = task_costs.tool_calls      + EXCLUDED.tool_calls,
    wall_time_ms    = task_costs.wall_time_ms    + EXCLUDED.wall_time_ms,
    compute_seconds = task_costs.compute_seconds + EXCLUDED.compute_seconds,
    amount_usd      = task_costs.amount_usd      + EXCLUDED.amount_usd,
    updated_at      = now()
`

type UpsertVersionCostParams struct {
	VersionID      pgtype.UUID    `json:"version_id"`
	TaskID         pgtype.UUID    `json:"task_id"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	CachedTokens   int64          `json:"cached_tokens"`
	ToolCalls      int32          `json:"tool_calls"`
	WallTimeMs     int64          `json:"wall_time_ms"`
	ComputeSeconds int64          `json:"compute_seconds"`
	AmountUsd      pgtype.Numeric `json:"amount_usd"`
}

// Sole writer to task_costs (task-cost-data-model §"Task Costs Aggregation
// Table"). Per-event aggregate increment; caller pre-resolves NULL→0 and
// per-kind column gating per spec §"Aggregate Increment Mapping Per Kind".
//
// task_id is deliberately ABSENT from DO UPDATE SET — task-cost-data-model
// §"Task Costs task_id is Immutable Per version_id" requires that a
// version_id's task ownership never migrate via the UPSERT. The settler
// pre-verifies via task_versions and DLQs on mismatch, so by the time we
// get here the supplied task_id is authoritative for an INSERT but
// redundant on UPDATE.
func (q *Queries) UpsertVersionCost(ctx context.Context, arg UpsertVersionCostParams) error {
	_, err := q.db.Exec(ctx, upsertVersionCost,
		arg.VersionID,
		arg.TaskID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.ToolCalls,
		arg.WallTimeMs,
		arg.ComputeSeconds,
		arg.AmountUsd,
	)
	return err
}
