// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTaskEvent = `-- name: InsertTaskEvent :exec
INSERT INTO task_events (
    task_id, version_id, run_id, seq, kind, payload
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (run_id, seq) DO NOTHING
`

type InsertTaskEventParams struct {
	TaskID    pgtype.UUID `json:"task_id"`
	VersionID pgtype.UUID `json:"version_id"`
	RunID     pgtype.UUID `json:"run_id"`
	Seq       int64       `json:"seq"`
	Kind      string      `json:"kind"`
	Payload   []byte      `json:"payload"`
}

// Idempotent on (run_id, seq). Duplicate inserts from the Realtime Gateway
// on Worker retries are silently dropped.
func (q *Queries) InsertTaskEvent(ctx context.Context, arg InsertTaskEventParams) error {
	_, err := q.db.Exec(ctx, insertTaskEvent,
		arg.TaskID,
		arg.VersionID,
		arg.RunID,
		arg.Seq,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, task_id, version_id, run_id, seq, kind, payload, created_at
FROM task_events
WHERE task_id = $1
  AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListEventsAfterParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	ID     int64       `json:"id"`
	Limit  int32       `json:"limit"`
}

// Pagination for WS gap-fill and HTTP replay: caller passes the highest
// event id it has already observed. Results are monotonically ordered by
// id; the (task_id, id) index supports the predicate. Pagination via LIMIT.
func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TaskEvent, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.TaskID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskEvent
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.VersionID,
			&i.RunID,
			&i.Seq,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionEventsAfter = `-- name: ListVersionEventsAfter :many
SELECT id, task_id, version_id, run_id, seq, kind, payload, created_at
FROM task_events
WHERE task_id = $1
  AND version_id = $2
  AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListVersionEventsAfterParams struct {
	TaskID    pgtype.UUID `json:"task_id"`
	VersionID pgtype.UUID `json:"version_id"`
	ID        int64       `json:"id"`
	Limit     int32       `json:"limit"`
}

// Version-scoped event backfill for the HTTP replay endpoint. Anchors on the
// existing (task_id, id) index (task_id equality + id range) and filters
// version_id as a residual predicate, so no new index is required. The caller
// passes the task_id resolved from the version plus the highest id seen.
func (q *Queries) ListVersionEventsAfter(ctx context.Context, arg ListVersionEventsAfterParams) ([]TaskEvent, error) {
	rows, err := q.db.Query(ctx, listVersionEventsAfter,
		arg.TaskID,
		arg.VersionID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskEvent
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.VersionID,
			&i.RunID,
			&i.Seq,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
