// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)::bigint AS total
FROM tasks
WHERE tenant_id = $1
  AND user_id = $2
  AND ($3::text IS NULL OR status = $3::text)
`

type CountTasksParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Status   *string     `json:"status"`
}

// Total count of the caller's tasks for offset pagination, using the same
// owner + optional-status predicate as ListTasks. Pass NULL for `status` to
// skip the filter.
func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, arg.TenantID, arg.UserID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, tenant_id, user_id, title, task_type, status, current_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, user_id, title, task_type, status, current_version, created_at, updated_at
`

type CreateTaskParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Title          string      `json:"title"`
	TaskType       string      `json:"task_type"`
	Status         string      `json:"status"`
	CurrentVersion pgtype.UUID `json:"current_version"`
}

// Insert a new task and return the row. The caller is responsible for ID
// generation and for choosing the initial `status` (typically 'pending').
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Title,
		arg.TaskType,
		arg.Status,
		arg.CurrentVersion,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.TaskType,
		&i.Status,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, tenant_id, user_id, title, task_type, status, current_version, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.TaskType,
		&i.Status,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, tenant_id, user_id, title, task_type, status, current_version, created_at, updated_at
FROM tasks
WHERE tenant_id = $1
  AND user_id = $2
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListTasksParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   *string     `json:"status"`
}

// Owner-scoped listing with an optional status filter. Pass NULL for `status`
// to skip the filter. Newest tasks first; pagination via LIMIT/OFFSET.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.TenantID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.TaskType,
			&i.Status,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskForControl = `-- name: LockTaskForControl :one
SELECT id, status, current_version, task_type
FROM tasks
WHERE id = $1 AND tenant_id = $2 AND user_id = $3
FOR UPDATE
`

type LockTaskForControlParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type LockTaskForControlRow struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	CurrentVersion pgtype.UUID `json:"current_version"`
	TaskType       string      `json:"task_type"`
}

// Acquires a row-level lock AND verifies ownership in one round-trip
// (add-task-control-api). Concurrent control requests for the same task
// serialise on this lock; the second handler observes the first's tx
// outcome before reading task.status. Owner predicate is inline so
// unknown OR unowned tasks return no rows — the caller maps
// pgx.ErrNoRows to ErrTaskNotFound for the identical 404 regardless of
// cause (mirrors task-read-api / task-cost-api). `task_type` is selected
// so the rollback `branch` path (add-task-rollback-api) gets everything it
// needs for createActiveVersion from this one owner-scoped lock, without an
// unscoped GetTaskByID re-read; the control caller ignores the column.
func (q *Queries) LockTaskForControl(ctx context.Context, arg LockTaskForControlParams) (LockTaskForControlRow, error) {
	row := q.db.QueryRow(ctx, lockTaskForControl, arg.ID, arg.TenantID, arg.UserID)
	var i LockTaskForControlRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentVersion,
		&i.TaskType,
	)
	return i, err
}

const lockTaskRow = `-- name: LockTaskRow :one
SELECT id, status, current_version
FROM tasks
WHERE id = $1
FOR UPDATE
`

type LockTaskRowRow struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	CurrentVersion pgtype.UUID `json:"current_version"`
}

// Acquires a row-level lock on a task and returns its id/status/current_version.
// Used by the iterate path so concurrent requests against the same task
// serialise behind one another inside the transaction.
func (q *Queries) LockTaskRow(ctx context.Context, id pgtype.UUID) (LockTaskRowRow, error) {
	row := q.db.QueryRow(ctx, lockTaskRow, id)
	var i LockTaskRowRow
	err := row.Scan(&i.ID, &i.Status, &i.CurrentVersion)
	return i, err
}

const switchTaskCurrentVersion = `-- name: SwitchTaskCurrentVersion :exec
UPDATE tasks
SET current_version = $2,
    updated_at = now()
WHERE id = $1
`

type SwitchTaskCurrentVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	CurrentVersion pgtype.UUID `json:"current_version"`
}

// Rollback `switch` mode (add-task-rollback-api): repoints `current_version`
// at a historical (terminal) version WITHOUT touching `tasks.status` —
// task-event-ingest stays the sole run-driven writer of status. Contrast with
// UpdateTaskCurrentVersion, which seeds status='pending' for a new run.
func (q *Queries) SwitchTaskCurrentVersion(ctx context.Context, arg SwitchTaskCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, switchTaskCurrentVersion, arg.ID, arg.CurrentVersion)
	return err
}

const updateTaskCurrentVersion = `-- name: UpdateTaskCurrentVersion :exec
UPDATE tasks
SET status = 'pending',
    current_version = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateTaskCurrentVersionParams struct {
	ID             pgtype.UUID `json:"id"`
	CurrentVersion pgtype.UUID `json:"current_version"`
}

// Points `tasks.current_version` at the new version and stamps the task back
// to `pending`. Called by the iterate transaction after `createActiveVersion`
// succeeds.
func (q *Queries) UpdateTaskCurrentVersion(ctx context.Context, arg UpdateTaskCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, updateTaskCurrentVersion, arg.ID, arg.CurrentVersion)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execrows
UPDATE tasks
SET status = $2,
    updated_at = now()
WHERE id = $1
  AND current_version = $3
  AND status NOT IN ('succeeded', 'failed', 'cancelled')
  AND status IS DISTINCT FROM $2
`

type UpdateTaskStatusParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	CurrentVersion pgtype.UUID `json:"current_version"`
}

// Event-ingest state-machine CAS (add-event-ingest-status-sync). Only the
// task's current (active) version may drive tasks.status, so the update is
// gated on current_version = $3 — a stale event for a superseded version is
// a no-op. Same terminal + real-transition guards as UpdateVersionStatus.
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status, arg.CurrentVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
