// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_costs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskCost = `-- name: GetTaskCost :one
SELECT
    $1::uuid                                                       AS task_id,
    COALESCE(SUM(input_tokens), 0)::bigint                                          AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint                                         AS output_tokens,
    COALESCE(SUM(cached_tokens), 0)::bigint                                         AS cached_tokens,
    COALESCE(SUM(tool_calls), 0)::int                                               AS tool_calls,
    COALESCE(SUM(wall_time_ms), 0)::bigint                                          AS wall_time_ms,
    COALESCE(SUM(compute_seconds), 0)::bigint                                       AS compute_seconds,
    COALESCE(SUM(amount_usd), 0)::numeric                                           AS amount_usd
FROM task_costs
WHERE task_id = $1
`

type GetTaskCostRow struct {
	TaskID         pgtype.UUID    `json:"task_id"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	CachedTokens   int64          `json:"cached_tokens"`
	ToolCalls      int32          `json:"tool_calls"`
	WallTimeMs     int64          `json:"wall_time_ms"`
	ComputeSeconds int64          `json:"compute_seconds"`
	AmountUsd      pgtype.Numeric `json:"amount_usd"`
}

// Task-level totals across all versions. Returns a single row with
// aggregated values (zeros when no rows match — COALESCE keeps the API
// caller from special-casing NULLs).
func (q *Queries) GetTaskCost(ctx context.Context, taskID pgtype.UUID) (GetTaskCostRow, error) {
	row := q.db.QueryRow(ctx, getTaskCost, taskID)
	var i GetTaskCostRow
	err := row.Scan(
		&i.TaskID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.ToolCalls,
		&i.WallTimeMs,
		&i.ComputeSeconds,
		&i.AmountUsd,
	)
	return i, err
}

const getVersionCost = `-- name: GetVersionCost :one
SELECT version_id, task_id, input_tokens, output_tokens, cached_tokens, tool_calls, wall_time_ms, compute_seconds, amount_usd, updated_at
FROM task_costs
WHERE version_id = $1
`

// One row per version. Returns no rows if the Cost Service hasn't yet
// upserted anything for the version (treat as "0 across the board").
func (q *Queries) GetVersionCost(ctx context.Context, versionID pgtype.UUID) (TaskCost, error) {
	row := q.db.QueryRow(ctx, getVersionCost, versionID)
	var i TaskCost
	err := row.Scan(
		&i.VersionID,
		&i.TaskID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.ToolCalls,
		&i.WallTimeMs,
		&i.ComputeSeconds,
		&i.AmountUsd,
		&i.UpdatedAt,
	)
	return i, err
}
