// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, tenant_id, user_id, title, task_type, status, current_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, user_id, title, task_type, status, current_version, created_at, updated_at
`

type CreateTaskParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Title          string      `json:"title"`
	TaskType       string      `json:"task_type"`
	Status         string      `json:"status"`
	CurrentVersion pgtype.UUID `json:"current_version"`
}

// Insert a new task and return the row. The caller is responsible for ID
// generation and for choosing the initial `status` (typically 'pending').
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Title,
		arg.TaskType,
		arg.Status,
		arg.CurrentVersion,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.TaskType,
		&i.Status,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, tenant_id, user_id, title, task_type, status, current_version, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Title,
		&i.TaskType,
		&i.Status,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, tenant_id, user_id, title, task_type, status, current_version, created_at, updated_at
FROM tasks
WHERE tenant_id = $1
  AND user_id = $2
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListTasksParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Status   *string     `json:"status"`
}

// Owner-scoped listing with an optional status filter. Pass NULL for `status`
// to skip the filter. Newest tasks first; pagination via LIMIT/OFFSET.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.TenantID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Title,
			&i.TaskType,
			&i.Status,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
