// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_checkpoints.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectLatestCheckpoint = `-- name: SelectLatestCheckpoint :one
SELECT id, run_id, step_seq, step_name, state, oss_key, created_at
FROM task_checkpoints
WHERE run_id = $1
ORDER BY step_seq DESC
LIMIT 1
`

// The highest-step_seq checkpoint for a run, or zero rows if none. Workers
// use this on resume to find the resume point.
func (q *Queries) SelectLatestCheckpoint(ctx context.Context, runID pgtype.UUID) (TaskCheckpoint, error) {
	row := q.db.QueryRow(ctx, selectLatestCheckpoint, runID)
	var i TaskCheckpoint
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepSeq,
		&i.StepName,
		&i.State,
		&i.OssKey,
		&i.CreatedAt,
	)
	return i, err
}
