// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, created_at, updated_at
FROM users
WHERE lower(email) = lower($1)
`

// Credential lookup for POST /auth/login. Matched case-insensitively against
// the users_email_lower_key index; the caller passes an already-lowercased
// email but lower($1) keeps the predicate aligned with the index regardless.
// Returns no rows for an unknown email; the repository maps pgx.ErrNoRows to
// identity.ErrUserNotFound (collapsed to ErrInvalidCredentials by the verifier).
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenant = `-- name: UpsertTenant :exec
INSERT INTO tenants (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type UpsertTenantParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Idempotent dev-seed of the tenant. Keyed on id so repeated boots converge;
// the name is left untouched on conflict (the seed only guarantees existence).
func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.Exec(ctx, upsertTenant, arg.ID, arg.Name)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, tenant_id, email, password_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    tenant_id     = EXCLUDED.tenant_id,
    email         = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    updated_at    = now()
`

type UpsertUserParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

// Idempotent dev-seed of the user. Keyed on id so repeated boots converge and a
// changed configured password refreshes the stored hash. password_hash holds a
// bcrypt digest — never the plaintext.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}
